version: '3'
services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "5173:5173"  # Map Vite dev server port
    depends_on:
      - backend

  backend:
    build:
      context: ./Server
    ports:
      - "5000:5000"  # Map backend port
    volumes:
      - ./Server:/app
    environment:
      - NODE_ENV=production
